### ISSUE TITLE
Make use the params attribute from requests

### ISSUE THREAD

**Issue by elcolumbio** [initBasti/python_plentymarkets_api#1]
Thank you for open sourcing so many cool projects.
I like this one, i would like to work on this in the future.

I can offer to refactor the code to something like requests.get(endpoint, params=query, data=data).
And query is a python dict.

I got a bug for the  vat endpoint with your code, when query is an empty string: rest/vat&page=2 and it should be rest/vat?page=2.
What do you think? If you agree, i am happy to make a pull request.

A quick fix would be:
if query == '': query = '?'  but i like using the requests params attribute more.

**Comment by initBasti** [comment]
> Thank you for open sourcing so many cool projects.
> I like this one, i would like to work on this in the future.

Thank you very much, those are mostly problem solutions for problems that I encountered at work, which I thought might be useful for other people too.

> I got a bug for the vat endpoint with your code when query is an empty string: rest/vat&page=2 and it should be rest/vat?page=2.
> What do you think? If you agree, I am happy to make a pull request.

Yes, that shouldn't happen...  I would be very happy if you open a pull request, so go ahead :+1: 

> I can offer to refactor the code to something like requests.get(endpoint, params=query, data=data).
> And query is a python dict.

Sure, I'm open to making the current implementation more general and cleaner. Please open a pull request for this idea and then we can discuss the details.

Greetings
